version: "3.9"

services:
  postgres:
    container_name: "postgres_cont"
    image: postgres:latest
    environment:
      POSTGRES_DB: "practice_system_db"
      POSTGRRES_USER: "Admin"
      POSTGRES_PASSWORD: "DefaultAdminPassword"
      PG_DATA: "/var/lib/postgresql/data"
    volumes:
      - ../2/ Init Database:/docker-entrypoint-initdb.d
      - practice-db-data:/var/lib/postgresql/data
    ports:
      - "5333:5333"
    networks:
      - postgres
  pgadmin:
    container_name: "pgadmin_cont"
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "default@mail.ru"
      PGADMIN_DEFAULT_PASSWORD: "DefaultPass"
      PGADMIN_DEFAULT_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped
    networks:
      - postgres
volumes:
  practice-db-data:
  pgadmin-data:
networks:
  postgres:
    driver: bridge