version: "3.9"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command:
      - go mod tidy
      - go run cmd/app/main.go
    networks:
      - golang-postgres-docker
  postgres:
    container_name: postgres_container
    image: postgres:latest
    environment:
      POSTGRES_DB: "testDbName"
      POSTGRES_USER: "testUsername"
      POSTGRES_PASSWORD: "testPass"
      PG_DATA: "/var/lib/postgresql/data"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - practicedb-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - golang-postgres-docker
  pgadmin:
    container_name: "pgadmin_container"
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "default@mail.ru"
      PGADMIN_DEFAULT_PASSWORD: "defaultPassword"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    networks:
      - golang-postgres-docker

volumes:
  practicedb-data:
  pgadmin-data:
networks:
  golang-postgres-docker:
    driver: bridge