basePath: /
definitions:
  practice_vgpek_internal_model_permissions.AddActionReq:
    properties:
      name:
        type: string
    type: object
  practice_vgpek_internal_model_permissions.AddObjectReq:
    properties:
      name:
        type: string
    type: object
  practice_vgpek_internal_model_permissions.AddObjectResp:
    properties:
      name:
        type: string
    type: object
  practice_vgpek_internal_model_permissions.AddPermReq:
    properties:
      actions_id:
        description: Слайс действий, которые над объектом может производить роль
        items:
          type: integer
        type: array
      object_id:
        type: integer
      role_id:
        type: integer
    type: object
  practice_vgpek_internal_model_permissions.AddPermResp:
    properties:
      added:
        $ref: '#/definitions/practice_vgpek_internal_model_permissions.AddPermReq'
    type: object
  practice_vgpek_internal_model_permissions.AddRoleReq:
    properties:
      name:
        type: string
    type: object
  practice_vgpek_internal_model_permissions.AddRoleResp:
    properties:
      name:
        type: string
    type: object
  practice_vgpek_internal_model_permissions.GetActionResp:
    properties:
      action_id:
        type: integer
      action_name:
        type: string
    type: object
  practice_vgpek_internal_model_permissions.GetActionsResp:
    properties:
      actions:
        items:
          $ref: '#/definitions/practice_vgpek_internal_model_permissions.GetActionResp'
        type: array
    type: object
  practice_vgpek_internal_model_permissions.GetObjectResp:
    properties:
      object_id:
        type: integer
      object_name:
        type: string
    type: object
  practice_vgpek_internal_model_permissions.GetObjectsResp:
    properties:
      objects:
        items:
          $ref: '#/definitions/practice_vgpek_internal_model_permissions.GetObjectResp'
        type: array
    type: object
  practice_vgpek_internal_model_permissions.GetRoleResp:
    properties:
      role_id:
        type: integer
      role_name:
        type: string
    type: object
  practice_vgpek_internal_model_permissions.GetRolesResp:
    properties:
      roles:
        items:
          $ref: '#/definitions/practice_vgpek_internal_model_permissions.GetRoleResp'
        type: array
    type: object
  practice_vgpek_internal_model_person.LogInReq:
    properties:
      login:
        type: string
      password:
        type: string
    required:
    - login
    - password
    type: object
  practice_vgpek_internal_model_person.LogInResp:
    properties:
      token:
        type: string
    type: object
  practice_vgpek_internal_model_person.RegisteredResp:
    properties:
      created_at:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      middle_name:
        type: string
    type: object
  practice_vgpek_internal_model_person.RegistrationReq:
    properties:
      first_name:
        type: string
      last_name:
        type: string
      login:
        type: string
      middle_name:
        type: string
      password:
        type: string
      registration_key:
        type: string
    type: object
  practice_vgpek_internal_model_registration_key.AddReq:
    properties:
      group_name:
        type: string
      max_count_usages:
        type: integer
      role_id:
        type: integer
    type: object
  practice_vgpek_internal_model_registration_key.AddResp:
    properties:
      body:
        type: string
      created_at:
        type: string
      current_count_usages:
        type: integer
      max_count_usages:
        type: integer
      reg_key_id:
        type: integer
    type: object
  practice_vgpek_internal_model_registration_key.DeleteReq:
    properties:
      key_id:
        type: integer
    type: object
  practice_vgpek_internal_model_registration_key.DeleteResp:
    properties:
      key_id:
        type: integer
    type: object
  practice_vgpek_pkg_apperr.AppError:
    properties:
      action:
        type: string
      error:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API для работы с практическими заданиями
  title: ВГПЭК API
  version: "1312.0"
paths:
  /action:
    post:
      consumes:
      - application/json
      description: Создает действие в системе
      operationId: create-action
      parameters:
      - description: Поля необходимые для создания действия
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/practice_vgpek_internal_model_permissions.AddActionReq'
      produces:
      - application/json
      responses:
        "200":
          description: Возвращает название созданного действия
          schema:
            $ref: '#/definitions/practice_vgpek_internal_model_permissions.AddObjectResp'
        default:
          description: ""
          schema:
            $ref: '#/definitions/practice_vgpek_pkg_apperr.AppError'
      security:
      - ApiKeyAuth: []
      summary: Создание действия
      tags:
      - Действие
  /action/params:
    get:
      consumes:
      - application/json
      description: Получение действий
      operationId: get-actions
      parameters:
      - description: Сколько выдать действия
        in: query
        name: limit
        type: integer
      - description: С какой позиции выдать действия
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Возвращает id и названия действия
          schema:
            $ref: '#/definitions/practice_vgpek_internal_model_permissions.GetActionsResp'
        default:
          description: ""
          schema:
            $ref: '#/definitions/practice_vgpek_pkg_apperr.AppError'
      security:
      - ApiKeyAuth: []
      summary: Получение действий по параметрам
      tags:
      - Действие
  /key:
    delete:
      consumes:
      - application/json
      description: Удаляет ключ регистрации
      operationId: delete-key
      parameters:
      - description: Поля необходимые для создания ключа
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/practice_vgpek_internal_model_registration_key.DeleteReq'
      produces:
      - application/json
      responses:
        "200":
          description: Возвращает id удаленного ключа
          schema:
            $ref: '#/definitions/practice_vgpek_internal_model_registration_key.DeleteResp'
        default:
          description: ""
          schema:
            $ref: '#/definitions/practice_vgpek_pkg_apperr.AppError'
      security:
      - ApiKeyAuth: []
      summary: удаление ключа регистрации
      tags:
      - ключ регистрации
    get:
      consumes:
      - application/json
      description: Удаляет ключ регистрации
      operationId: get-key
      parameters:
      - description: Сколько выдать ключей
        in: query
        name: limit
        type: integer
      - description: С какой позиции выдать ключи
        in: query
        name: offset
        type: integer
      - description: выдавать ключи валидные/невалидные
        in: query
        name: valid
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: Возвращает id удаленного ключа
          schema:
            $ref: '#/definitions/practice_vgpek_internal_model_registration_key.DeleteResp'
        default:
          description: ""
          schema:
            $ref: '#/definitions/practice_vgpek_pkg_apperr.AppError'
      security:
      - ApiKeyAuth: []
      summary: получение ключей регистрации
      tags:
      - ключ регистрации
    post:
      consumes:
      - application/json
      description: Создает ключ регистрации
      operationId: create-key
      parameters:
      - description: Поля необходимые для создания ключа
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/practice_vgpek_internal_model_registration_key.AddReq'
      produces:
      - application/json
      responses:
        "200":
          description: Возвращает id ключа в системе, его тело, кол-во использований
            и когда был создан
          schema:
            $ref: '#/definitions/practice_vgpek_internal_model_registration_key.AddResp'
        default:
          description: ""
          schema:
            $ref: '#/definitions/practice_vgpek_pkg_apperr.AppError'
      security:
      - ApiKeyAuth: []
      summary: Создание ключа регистрации
      tags:
      - ключ регистрации
  /login:
    post:
      consumes:
      - application/json
      description: Вход в систему (возвращает jwt bearer token)
      operationId: login
      parameters:
      - description: Поля необходимые для авторизации
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/practice_vgpek_internal_model_person.LogInReq'
      produces:
      - application/json
      responses:
        "200":
          description: Token для авторизации
          schema:
            $ref: '#/definitions/practice_vgpek_internal_model_person.LogInResp'
        default:
          description: ""
          schema:
            $ref: '#/definitions/practice_vgpek_pkg_apperr.AppError'
      summary: Авторизация
      tags:
      - авторизация
  /object:
    get:
      consumes:
      - application/json
      description: Получение объекта действия по id
      operationId: get-object
      parameters:
      - description: ID объекта
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Возвращает id и название объекта
          schema:
            $ref: '#/definitions/practice_vgpek_internal_model_permissions.GetObjectResp'
        default:
          description: ""
          schema:
            $ref: '#/definitions/practice_vgpek_pkg_apperr.AppError'
      security:
      - ApiKeyAuth: []
      summary: Получение объекта действия
      tags:
      - Объект действия
    post:
      consumes:
      - application/json
      description: Создает объект действия в системе
      operationId: create-object
      parameters:
      - description: Поля необходимые для создания объекта
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/practice_vgpek_internal_model_permissions.AddObjectReq'
      produces:
      - application/json
      responses:
        "200":
          description: Возвращает название созданной роли
          schema:
            $ref: '#/definitions/practice_vgpek_internal_model_permissions.AddObjectResp'
        default:
          description: ""
          schema:
            $ref: '#/definitions/practice_vgpek_pkg_apperr.AppError'
      security:
      - ApiKeyAuth: []
      summary: Создание объекта действия
      tags:
      - Объект действия
  /object/params:
    get:
      consumes:
      - application/json
      description: Получение объектов
      operationId: get-objects
      parameters:
      - description: Сколько выдать ролей
        in: query
        name: limit
        type: integer
      - description: С какой позиции выдать роли
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Возвращает id и названия объектов
          schema:
            $ref: '#/definitions/practice_vgpek_internal_model_permissions.GetObjectsResp'
        default:
          description: ""
          schema:
            $ref: '#/definitions/practice_vgpek_pkg_apperr.AppError'
      security:
      - ApiKeyAuth: []
      summary: Получение объектов по параметрам
      tags:
      - Объект действия
  /permissions:
    post:
      consumes:
      - application/json
      description: Назначает права действия
      operationId: add-perm
      parameters:
      - description: Поля назначении у роли к объекту действий
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/practice_vgpek_internal_model_permissions.AddPermReq'
      produces:
      - application/json
      responses:
        "200":
          description: Возвращает id роли, id объекта и id действий, к ним добавленные
          schema:
            $ref: '#/definitions/practice_vgpek_internal_model_permissions.AddPermResp'
        default:
          description: ""
          schema:
            $ref: '#/definitions/practice_vgpek_pkg_apperr.AppError'
      security:
      - ApiKeyAuth: []
      summary: Назначение доступов
      tags:
      - доступы
  /registration:
    post:
      consumes:
      - application/json
      description: Cоздает аккаунт по ключу регистрации
      operationId: create-person
      parameters:
      - description: Поля необходимые для регистрации
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/practice_vgpek_internal_model_person.RegistrationReq'
      produces:
      - application/json
      responses:
        "200":
          description: На кого зарегестрирован аккаунт и кем
          schema:
            $ref: '#/definitions/practice_vgpek_internal_model_person.RegisteredResp'
        default:
          description: ""
          schema:
            $ref: '#/definitions/practice_vgpek_pkg_apperr.AppError'
      summary: Регистрация
      tags:
      - авторизация
  /role:
    post:
      consumes:
      - application/json
      description: Создает роль в системе
      operationId: create-role
      parameters:
      - description: Поля необходимые для создания роли
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/practice_vgpek_internal_model_permissions.AddRoleReq'
      produces:
      - application/json
      responses:
        "200":
          description: Возвращает название созданной роли
          schema:
            $ref: '#/definitions/practice_vgpek_internal_model_permissions.AddRoleResp'
        default:
          description: ""
          schema:
            $ref: '#/definitions/practice_vgpek_pkg_apperr.AppError'
      security:
      - ApiKeyAuth: []
      summary: Создание роли
      tags:
      - Роль
  /role/params:
    get:
      consumes:
      - application/json
      description: Получение ролей
      operationId: get-roles
      parameters:
      - description: Сколько выдать ролей
        in: query
        name: limit
        type: integer
      - description: С какой позиции выдать роли
        in: query
        name: offset
        type: integer
      - description: ID ключа
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Возвращает id и названия ролей
          schema:
            $ref: '#/definitions/practice_vgpek_internal_model_permissions.GetRolesResp'
        default:
          description: ""
          schema:
            $ref: '#/definitions/practice_vgpek_pkg_apperr.AppError'
      security:
      - ApiKeyAuth: []
      summary: Получение ролей по параметрам
      tags:
      - Роль
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
